---
- name: kitty
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: packages
      become: true
      ignore_errors: true
      ansible.builtin.apt:
        pkg:
          - kitty

    - name: config
      ansible.builtin.template:
        src: ../templates/kitty.conf.j2
        dest: /home/eulegang/.config/kitty/kitty.conf
        owner: eulegang
        group: eulegang
        mode: '0644' 

