---
- name: neovim
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: packages
      become: true
      ignore_errors: true
      ansible.builtin.apt:
        pkg:
          - gcc
          - build-essential
          - gettext
          - cmake
          - ninja-build

    - name: fetch neovim
      ansible.builtin.git:
        repo: 'https://github.com/neovim/neovim'
        force: true
        dest: /home/eulegang/external/neovim
        version: master

    - name: build neovim deps
      ansible.builtin.shell: 
        chdir: /home/eulegang/external/neovim
        creates: /home/eulegang/external/neovim/.deps/usr
        cmd: |
          mkdir -p .deps
          cd .deps 
          cmake -DCMAKE_BUILD_TYPE=Release -G Ninja ../cmake.deps
          ninja


    - name: build neovim
      ansible.builtin.shell: 
        chdir: /home/eulegang/external/neovim
        creates: /home/eulegang/external/neovim/build/bin/nvim
        cmd: |
          mkdir -p build
          cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja .
          cd build
          ninja

    - name: install neovim
      become: true
      command:
        chdir: /home/eulegang/external/neovim/build
        creates: /usr/local/bin/nvim
        cmd: 'ninja install'


