---
- name: rust
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: dev packages
      become: true
      ansible.builtin.apt:
        pkg:
          - libssl-dev

    - name: check rustup
      stat:
        path: /home/eulegang/.cargo/bin
      register: cargo

    - name: install rust
      when: not cargo.stat.exists
      command:
        cmd: 'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh'

    - name: starship
      command:
        cmd: 'cargo install starship'
        creates: '/home/eulegang/.cargo/bin/starship'

    - name: ripgrep
      command:
        cmd: 'cargo install ripgrep'
        creates: '/home/eulegang/.cargo/bin/rg'

    - name: hexyl
      command:
        cmd: 'cargo install hexyl'
        creates: '/home/eulegang/.cargo/bin/hexyl'

    - name: fd
      command:
        cmd: 'cargo install fd-find'
        creates: '/home/eulegang/.cargo/bin/fd'

    - name: exa
      command:
        cmd: 'cargo install exa'
        creates: '/home/eulegang/.cargo/bin/exa'

    - name: delta
      command:
        cmd: 'cargo install git-delta'
        creates: '/home/eulegang/.cargo/bin/delta'

    - name: cargo-watch
      command:
        cmd: 'cargo install cargo-watch'
        creates: '/home/eulegang/.cargo/bin/cargo-watch'

    - name: cargo-nextest
      command:
        cmd: 'cargo install cargo-nextest'
        creates: '/home/eulegang/.cargo/bin/cargo-nextest'

    - name: cargo-tarpaulin
      command:
        cmd: 'cargo install cargo-tarpaulin'
        creates: '/home/eulegang/.cargo/bin/cargo-tarpaulin'

    - name: dedbg
      command:
        cmd: 'cargo install dedbg'
        creates: '/home/eulegang/.cargo/bin/dedbg'

    - name: fetch rust-analyzer
      ansible.builtin.git: 
        force: true
        repo: 'https://github.com/rust-lang/rust-analyzer'
        dest: /home/eulegang/external/rust-analyzer
  
    - name: build rust-analyzer
      command:
        cmd: 'cargo xtask install --server'
        chdir: /home/eulegang/external/rust-analyzer
        creates: /home/eulegang/.cargo/bin/rust-analyzer


